apiVersion: cnat.programming-kubernetes.info/v1alpha1
kind: At
metadata:
  labels:
    app.kubernetes.io/name: at
    app.kubernetes.io/instance: at-sample
    app.kubernetes.io/part-of: cnat-kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cnat-kubebuilder
  name: example-at
spec:
  schedule: "2023-04-30T08:01:00Z"
  command: "echo HEY"
